function [ Btx_1, Bty_1, Btz_1 ] = F_BodyFrame_XYZ( dis, angle , fitresult_alpha, fitresult_beta)
%F_BODYFRAME_XYZ 此处显示有关此函数的摘要
%   此处显示详细说明
%   L: 斜距
%   angle: 
% dis 测距 angle 测角单位弧度
angle = deg2rad(angle);
dRx = fitresult_alpha.a0 + ...
    fitresult_alpha.a1*sin(1*angle+fitresult_alpha.b1)+...
    fitresult_alpha.a2*sin(2*angle+fitresult_alpha.b2)+...
    fitresult_alpha.a3*sin(3*angle+fitresult_alpha.b3)+...
    fitresult_alpha.a4*sin(4*angle+fitresult_alpha.b4)+...
    fitresult_alpha.a5*sin(5*angle+fitresult_alpha.b5)+...
    fitresult_alpha.a6*sin(6*angle+fitresult_alpha.b6)+...
    fitresult_alpha.a7*sin(7*angle+fitresult_alpha.b7)+...
    fitresult_alpha.a8*sin(8*angle+fitresult_alpha.b8);
dRy = fitresult_beta.a0 + ...
    fitresult_beta.a1*sin(1*angle+fitresult_beta.b1)+...
    fitresult_beta.a2*sin(2*angle+fitresult_beta.b2)+...
    fitresult_beta.a3*sin(3*angle+fitresult_beta.b3)+...
    fitresult_beta.a4*sin(4*angle+fitresult_beta.b4)+...
    fitresult_beta.a5*sin(5*angle+fitresult_beta.b5)+...
    fitresult_beta.a6*sin(6*angle+fitresult_beta.b6)+...
    fitresult_beta.a7*sin(7*angle+fitresult_beta.b7)+...
    fitresult_beta.a8*sin(8*angle+fitresult_beta.b8);
dRz = sqrt(1 - dRx.^2 - dRy.^2);

Btx = dis .* dRx;
Bty = dis .* dRy;
Btz = dis .* dRz;

Btx_1 = Btx;
Bty_1 = Bty;
Btz_1 = Btz;

end

